language: node_js
env:
  - PGDATABASE=store_manager
  - PGUSER=postgres
  - JWTKEY=secretKey
  - PGHOST=localhost
  - PGPORT=5432
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'DROP DATABASE IF EXISTS store_manager;' -U postgres
  - psql -c 'create database store_manager;' -U postgres
  - psql -c "CREATE USER otaigbe WITH PASSWORD 'password';" -U postgres
script:
  - npm run travistest
after_script:
  - psql -c 'select * from products;' -U postgres
  - psql -c 'select * from attendants;' -U postgres