language: node_js
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'DROP DATABASE IF EXISTS store_manager;' -U postgres
  - psql -c 'create database store_manager;' -U postgres
env:
  - PGUSER=postgres
  - PGHOST=localhost
script:
  - npm run test
after_success:
  - nyc report --reporter=text-lcov | coveralls
