language: node_js
env:
  global:
  - PGDATABASE=store_manager
  - PGUSER=postgres
  - JWTKEY='secretKey'
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'create database store_manager;' -U postgres
script:
  - npm run travistest
