language: node_js
node_js:
    - "10"
services:
  - postgresql
script:
  - npm run test
  - psql -U postgres 'select * from products';

env:
 - PGUSER = postgres
 - PGDATABASE = store_manager
 - PGPORT = 5432
 - PGPASSWORD= password
 - PORT = 5500
 - JWTKEY = secretKey
after_success: npm run coverage
