language: node_js
node_js:
    - "10"
services:
  - postgresql
script:
  - psql -c 'create database store_manager;' -U postgres
  - export PGPASSWORD = password
  - psql -U postgres -a -f dbscripts/travis.sql

env:
 - NODE_ENV= test
 - PGUSER = postgres
 - PGDATABASE = store_manager
 - PGPORT = 5432
 - PGPASSWORD= password
 - PORT = 5500
 - JWTKEY = secretKey
after_success: npm run coverage
