language: node_js
node_js:
    - "10"
services:
  - postgresql
script: npm test
before_script:
  - psql -c 'create database store_manager;' -U postgres
  - psql -c "CREATE USER postgrestravis WITH PASSWORD 'mar889003';" -U postgres
after_success: npm run coverage
