language: node_js
env:
  - PGUSER=postgres
  - JWTKEY=secretKey
  - PGHOST=localhost
  - PGPASSWORD=
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'DROP DATABASE IF EXISTS store_manager;' -U postgres
  - psql -c 'create database store_manager;' -U postgres
script:
  - npm run travistest