language: node_js
env:
  - PGUSER=postgres
  - JWTKEY=secretKey
  - PGHOST=localhost
  - PGPASSWORD=
  - PGDATABASE=storemanager
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'DROP DATABASE IF EXISTS storemanager;' -U postgres
  - psql -c 'create database storemanager;' -U postgres
script:
  - npm run travistest