const products = [{
  Id: '3',
  Name: 'Gino tomato paste',
  Brand: 'Gino',
  Price: '50',
  QuantitySupplied: '400',
  Supplier: 'daniel',
  'Date-of-Creation': '2018-10-15',
  Category: 'can foods',
},
{
  Id: '1',
  Name: 'Heinz Baked beans',
  Brand: 'Heinz',
  Price: '12.50',
  QuantitySupplied: '400',
  Supplier: 'Olu',
  'Date-of-Creation': '2018-10-17',
  Category: 'can foods',
},
{
  Id: '2',
  Name: 'Teatime chocolate biscuits',
  Brand: 'heinz',
  Price: '1.20',
  QuantitySupplied: '400',
  Supplier: 'Olu',
  'Date-of-Creation': '2018-10-17',
  Category: 'can foods',
},
{
  Id: '5',
  Name: 'RichTea chocolate biscuits',
  Brand: 'Mctivities',
  Price: '1.20',
  QuantitySupplied: '40 cartons of 50 pieces each',
  Supplier: 'Olu',
  'Date-of-Creation': '2018-10-17',
  Category: 'Cookies',
},
];

export default products;
